# Generated by Django 4.2 on 2023-06-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('jobTitle', models.CharField(max_length=50)),
                ('shortDescription', models.CharField(max_length=300)),
                ('linkedIn', models.URLField(null=True)),
                ('github', models.URLField(null=True)),
                ('mail', models.EmailField(max_length=254)),
                ('aboutMe', models.CharField(max_length=5000, null=True)),
                ('skills', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
