# Generated by Django 4.2 on 2023-06-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='aboutMe',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='github',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='linkedIn',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='skills',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='user_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
