# Generated by Django 4.2 on 2023-06-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_portfolio_aboutme_remove_portfolio_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='profilePic',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
