# Generated by Django 4.2 on 2023-06-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_portfolio_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='porfolioTemplate',
            field=models.CharField(choices=[('BLUE', 'Blue Theme'), ('CREAM', 'Elegent Cream'), ('DEFAULT', 'Default Theme')], default='DEFAULT', max_length=10),
        ),
    ]
