# Generated by Django 4.2 on 2023-06-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_portfolio_porfoliotemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='name',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='github',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='linkedIn',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='mail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='twitter',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='shortDescription',
            field=models.TextField(),
        ),
    ]
